### ISSUE TITLE
Can/should parallel estimation of independent responses be optimized?

### ISSUE THREAD

**Issue by christianbrodbeck** [LBHB/NEMS0#95]
While using the filter-bank model to estimate responses at each (MEG) sensor to one stimulus, I realized this seems to be very slow, and, much slower than it ought to be. To give an example, estimating the 157 signals independently with `fir1x80` took 28.5 s, while estimating them jointly with `fir157x1x80` took 1431.7 s. I assume that is because the optimization is also searching for interaction effects between different filters in the bank, which in this special case never affect the outcome. Is there a way to recognize or explicitly specify such a special case? Or is there maybe a better way to specify the model?

**Comment by svdavid** [comment]
Yes, this is an important problem. Two scenarios. @christianbrodbeck Can you give me a sense of which one reflects your situation?

1. In one case, the parallel channels really are independent models, in that the stimulus signals travel through separate filters to predict each response channel. IN this case there really is no benefit to fitting them all simultaneously. Is it still convenient to combine them in a single model?

2. Alternatively, we might want to project the stimulus into a subspace and use that representation to predict all the response channels. In that case, the subspace should be fit to all the channel and they aren't independent any more. This is a problem I've started working on, at least implementing the model. However, it is slow to fit them. I've heard that you can use a form of drop-out, where you iterate across subsets of channels.  Eg, take 80/157 channels, fit for a while, then take a different random subset of 80, fit for a while, etc.  Is this something you've pursued in the past? Or would be interested in pursuing? I think it'd be a great feature for NEMS. 

Unfortunately, there's no obvious way of doing channel drop-out. I've hacked a few things together, but nothing beautiful yet. I'm very much open to ideas!

**Comment by christianbrodbeck** [comment]
For our case with MEG the channels area clearly dependent, so a solution like (2) would definitely be desirable. But a solution like (1) might always be useful as a baseline to compare how much variance a solution (2) explains?  Also, so far I’ve treated each channel independently and then used multiple comparison correction on the results (and that’s a common solution for MEG/EEG). So it would be useful to have an easy way to specify models of type (1) without incurring the fitting time penalty. But it might not be straight forward to infer for a general case which channels are dependent and which are not, so maybe a better way for the API would be to specify a single channel model for a multiple channel recording?

**Comment by svdavid** [comment]
We do typically analyze one channel at a time. The unique identifier for a model is `cellid, batch, modelname`, where 
* cellid = "experiment-electrode-unit" -- since it's possible sometimes to isolate more than one single unit from a single electrode. A similar scheme could be used for MEG data.
* batch = group of recordings from a single experiment type. Eg, "tone detection in noise behavior, recorded from A1"
* modelname = string specifying a unique preprocesser, modelspec and fit algorithm.

However, I am very much interested in option 2, looking at ways to efficiently fit models for simultaneous recordings, where part of the model might be shared across channels, which part might be channel-specific. I haven't found a pretty way to code up this sort of model yet, but I want to start playing around with ideas more systematically. I agree, for now, we can depend on the user to provide direction on which sort of model/fit strategy to use.

**Comment by svdavid** [comment]
@christianbrodbeck It's taken a while, but this issue has been addressed at least in a first pass in `nems_db.nems_lbhb.fit_wrappers.fit_population_iteratively()` and `.fit_population_slice()` These functions are not completely general, but they are able to fit filters for separate channels much more efficiently by iterating through and optimizing each individually. fit_population_iteratively is useful for me because it combines fitting of common elements and the channel specific elements looping series of small iterations. Would be happy to discuss if this is an area you'd like to pursue.
